### PR TITLE
Update qm-qua version to 1.2.2

### LINKED ISSUE #2: Outdated version of `qm-qua`
In the pyproject we are currently using `qm-qua==1.2.1` however with this version I'm getting the following error.

```sh
Traceback (most recent call last):
  File "/nfs/users/andrea.pasquale/default/bin/qq", line 6, in <module>
    sys.exit(command())
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/cli/_base.py", line 77, in run
    protocols_execution(runcard, folder, force, update)
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/cli/run.py", line 44, in protocols_execution
    history = runcard.run(
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/auto/runcard.py", line 62, in run
    instance.run_protocol(
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/auto/execute.py", line 128, in run_protocol
    completed = task.run(
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/auto/task.py", line 165, in run
    completed.data, completed.data_time = operation.acquisition(
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/auto/operation.py", line 40, in wrapper
    out = func(*args, **kwds)
  File "/nfs/users/andrea.pasquale/qibocal/src/qibocal/protocols/classification/classification.py", line 256, in _acquisition
    results.update(platform.execute([sequence], **options))
  File "/nfs/users/andrea.pasquale/qibolab/src/qibolab/_core/platform/platform.py", line 275, in execute
    results |= self._execute(b, options, configs, sweepers)
  File "/nfs/users/andrea.pasquale/qibolab/src/qibolab/_core/platform/platform.py", line 209, in _execute
    new_result = instrument.play(configs, sequences, options, sweepers)
  File "/nfs/users/andrea.pasquale/qibolab/src/qibolab/_core/instruments/qm/controller.py", line 573, in play
    result = self.execute_program(experiment)
  File "/nfs/users/andrea.pasquale/qibolab/src/qibolab/_core/instruments/qm/controller.py", line 528, in execute_program
    machine = self.manager.open_qm(asdict(self.config))
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/qm/quantum_machines_manager.py", line 321, in open_qm
    loaded_config = load_config_from_calibration_db(
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/qm/_octaves_container.py", line 200, in load_config_from_calibration_db
    lo_cal = calibration_db.get_lo_cal(octave_channel, lo_freq, output_gain)
  File "/nfs/users/andrea.pasquale/default/lib/python3.10/site-packages/qm/octave/calibration_db.py", line 234, in get_lo_cal
    lo_cal_obj = LOCalibrationDBSchema(**lo_cal)
TypeError: LOCalibrationDBSchema.__init__() missing 1 required positional argument: 'lo_mode_id'
```
After discussing with @Edoardo-Pedicillo we suggested me to upgrade `qm-qua` and it seems to be working with `qm-qua==1.2.2`.
We should probably modify the version also in this repo.

### PR DESCRIPTION
**Pull request by stavros11**
Fixes #2. Apparently 1.2.3 is still in pre-release stage, therefore I sticked to 1.2.2 which is the one I have also used with both our clusters and it should work. Thanks @andrea-pasquale for pointing that out.

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]
Thanks @stavros11

**Comment by stavros11** [comment]
I also pushed the qibolab version to the latest (0.2.9). This required to drop support for py3.9.

**Review by alecandido — APPROVED** [review]
